[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.14.1",
    "anthropic>=0.45.2",
    "beautifulsoup4>=4.13.3",
    "joblib>=1.4.2",
    "keras>=2.14.0",
    "lightgbm>=4.5.0",
    "numpy>=2.2.2",
    "openai>=1.61.1",
    "pandas>=2.2.3",
    "plotly>=6.0.0",
    "praw>=7.8.1",
    "psycopg2-binary>=2.9.10",
    "pyserum>=0.5.0a0",
    "requests>=2.32.3",
    "scikit-learn>=1.6.1",
    "solana>=0.25.1",
    "solana-sdk>=0.25.6",
    "sqlalchemy>=2.0.38",
    "streamlit>=1.42.0",
    "telethon>=1.38.1",
    "tensorflow>=2.14.0",
    "tweepy>=4.15.0",
    "twilio>=9.4.4",
    "xgboost>=2.1.4",
    "yfinance>=0.2.52",
]
