[server]
headless = true
address = "0.0.0.0"
port = 5001
enableCORS = true
enableXsrfProtection = false

[theme]
primaryColor = "#ffd700"
backgroundColor = "#000000"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#ffd700"

[logger]
level = "info"