[server]
port = 5000
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
headless = true

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"

[browser]
serverAddress = "0.0.0.0"
serverPort = 5000
gatherUsageStats = false

[logger]
level = "info"
messageFormat = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[client]
toolbarMode = "minimal"
showErrorDetails = true

[runner]
magicEnabled = true
fastReruns = true
