
[theme]
primaryColor = "#FFD700"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"

[server]
port = 5000
address = "0.0.0.0"
headless = true
enableCORS = true
enableXsrfProtection = false
enableWebsocketCompression = true

[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = false
serverPort = 5000
