[theme]
primaryColor = "#FFD700"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"

[server]
port = 5000
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = true
baseUrlPath = ""

[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = false

[logger]
level = "info"
